# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zs7fD4Q4LPcVSbqVMzpJds0JZKbE4xJ0
"""

import pandas as pd
import numpy as np
import streamlit as st
import pickle

st.title("Music Streaming Service Churn Prediction")
    
age = st.number_input("Age", 10, 80, 25)
subscription = st.selectbox("Subscription Type", ["Free", "Premium"])
listening_time = st.number_input("Avg Listening Time (mins/day)", 0, 300, 60)
skips = st.number_input("Avg Skips per Day", 0, 100, 5)

input_data = np.array([[age, subscription_encoded, listening_time, skips]])
input_scaled = scaler.transform(input_data)
prediction = model.predict(input_scaled)
churn_status = le.inverse_transform(prediction)
st.success(f"✅ Prediction: **{churn_status[0]}**")